# Generated by Django 3.0.3 on 2020-08-18 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text='使用者姓名', max_length=6)),
                ('age', models.IntegerField(default=0)),
                ('birth_day', models.DateTimeField(null=True)),
                ('pic_url', models.URLField(null=True, verbose_name='會員的照片網址')),
                ('email', models.EmailField(max_length=254, null=True)),
                ('is_female', models.BooleanField()),
                ('last_modify_date', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-age', 'is_female'],
            },
        ),
    ]
